### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by faeldray** [faeldray/DefsLTS#1]
Doable:
- [x] Allow any glue to be used in recipes instead of just wood glue
- [x] Reduce the amount of briquettes needed in recipes
- [x] Create charcoal recipe that uses a lot of materials to get started on charcoal stuff
- [x] Pine tar shouldn't need so many damn pine cones, and should also allow vanilla pine cones
- [x] Add recipes for mayo bottles, remoulade bottles, and bowls
- [x] [Rename distillation equipment recipe](https://github.com/DefbeatCZ/DefsLTS/issues/21)
- [x] [Add recipe to turn unusable metal into scrap metal](https://github.com/DefbeatCZ/DefsLTS/issues/30)
- [x] Scrapping broken axe fails to destroy the axe. Probably due to how broken items change the instance. Try using destroy
- [x] [Craftable gunpowder](https://github.com/DefbeatCZ/DefsLTS/pull/27)

Possible future features:
- [ ] Add ability to turn off used literature (interferes with other mods)
- [ ] Scrapping recipes should exclude favorite items _(looks like this is vanilla behavior. Not sure how to fix it. Perhaps separating the recipes by item type will reduce scrapping by accident.)_
- [ ] butchering as world interaction
- [ ] Split mod into smaller ones
- [ ] Add oats to grow and make into cans/bowls of oatmeal and flour
- [ ] Remove trunk size increase (there's many other mods that do this already and are more customizable)
- [ ] Recipe for bio-diseal. There's already a distiller so why not?
- [ ] Beehives! Could be a great way to make farmable honey/sugar

Not going to complete:
- When trying to forge something, e.g. 'LTS Forge Barbed Wire' the recipe has the Welder Mask greyed out until it is no longer marked as Favorite _(looks like this is vanilla behavior. Not sure how to fix it)_
